name: Asia

on: [workflow_dispatch]

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Build :latest
        if: success()
        run: make asia
